import dotenv from 'dotenv';
dotenv.config();
import mongoose from 'mongoose';

const Stock = mongoose.model('Stock', new mongoose.Schema({
  id: Number, ticker: String, exchange: String, name: String,
  initialPrice: Number, currentPrice: Number, description: String,
  ipoDate: String, siteUrl: String, industries: [String],
  icon: String, favorited: Boolean
}));

const stocks = [
  { id: 1, ticker: 'AAPL', exchange: 'NASDAQ', name: 'Apple Inc.', initialPrice: 150, currentPrice: 150, description: 'Technology company that designs consumer electronics and software.', ipoDate: '1980-12-12', siteUrl: 'https://apple.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=apple.com&sz=128', favorited: false },
  { id: 2, ticker: 'TSLA', exchange: 'NASDAQ', name: 'Tesla Inc.', initialPrice: 900, currentPrice: 900, description: 'Electric vehicle and clean energy company.', ipoDate: '2010-06-29', siteUrl: 'https://tesla.com', industries: ['Automotive'], icon: 'https://www.google.com/s2/favicons?domain=tesla.com&sz=128', favorited: false },
  { id: 3, ticker: 'MSFT', exchange: 'NASDAQ', name: 'Microsoft Corp.', initialPrice: 300, currentPrice: 300, description: 'Corporation that develops software, hardware and cloud services.', ipoDate: '1986-03-13', siteUrl: 'https://microsoft.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128', favorited: false },
  { id: 4, ticker: 'GOOGL', exchange: 'NASDAQ', name: 'Alphabet Inc.', initialPrice: 2800, currentPrice: 2800, description: 'Technology company specializing in internet services and products.', ipoDate: '2004-08-19', siteUrl: 'https://google.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=google.com&sz=128', favorited: false },
  { id: 5, ticker: 'AMZN', exchange: 'NASDAQ', name: 'Amazon.com Inc.', initialPrice: 3400, currentPrice: 3400, description: 'Multinational technology company focusing on e-commerce and cloud.', ipoDate: '1997-05-15', siteUrl: 'https://amazon.com', industries: ['E-Commerce'], icon: 'https://www.google.com/s2/favicons?domain=amazon.com&sz=128', favorited: false },
  { id: 6, ticker: 'META', exchange: 'NASDAQ', name: 'Meta Platforms Inc.', initialPrice: 330, currentPrice: 330, description: 'Social media and technology conglomerate behind Facebook.', ipoDate: '2012-05-18', siteUrl: 'https://meta.com', industries: ['Social Media'], icon: 'https://www.google.com/s2/favicons?domain=meta.com&sz=128', favorited: false },
  { id: 7, ticker: 'NFLX', exchange: 'NASDAQ', name: 'Netflix Inc.', initialPrice: 550, currentPrice: 550, description: 'Streaming entertainment service company worldwide.', ipoDate: '2002-05-23', siteUrl: 'https://netflix.com', industries: ['Entertainment'], icon: 'https://www.google.com/s2/favicons?domain=netflix.com&sz=128', favorited: false },
  { id: 8, ticker: 'NVDA', exchange: 'NASDAQ', name: 'NVIDIA Corporation', initialPrice: 220, currentPrice: 220, description: 'Company designing graphics processing units and AI chips.', ipoDate: '1999-01-22', siteUrl: 'https://nvidia.com', industries: ['Semiconductors'], icon: 'https://www.google.com/s2/favicons?domain=nvidia.com&sz=128', favorited: false },
  { id: 9, ticker: 'JPM', exchange: 'NYSE', name: 'JPMorgan Chase and Co.', initialPrice: 160, currentPrice: 160, description: 'Multinational investment bank and financial services company.', ipoDate: '1978-01-01', siteUrl: 'https://jpmorganchase.com', industries: ['Banking'], icon: 'https://www.google.com/s2/favicons?domain=jpmorganchase.com&sz=128', favorited: false },
  { id: 10, ticker: 'DIS', exchange: 'NYSE', name: 'The Walt Disney Company', initialPrice: 175, currentPrice: 175, description: 'Multinational mass media and entertainment conglomerate.', ipoDate: '1957-11-12', siteUrl: 'https://disney.com', industries: ['Entertainment'], icon: 'https://www.google.com/s2/favicons?domain=disney.com&sz=128', favorited: false },
  { id: 11, ticker: 'BABA', exchange: 'NYSE', name: 'Alibaba Group', initialPrice: 200, currentPrice: 200, description: 'Chinese multinational e-commerce and technology company.', ipoDate: '2014-09-19', siteUrl: 'https://alibaba.com', industries: ['E-Commerce'], icon: 'https://www.google.com/s2/favicons?domain=alibaba.com&sz=128', favorited: false },
  { id: 12, ticker: 'V', exchange: 'NYSE', name: 'Visa Inc.', initialPrice: 230, currentPrice: 230, description: 'Multinational payment card services corporation.', ipoDate: '2008-03-19', siteUrl: 'https://visa.com', industries: ['Finance'], icon: 'https://www.google.com/s2/favicons?domain=visa.com&sz=128', favorited: false },
  { id: 13, ticker: 'WMT', exchange: 'NYSE', name: 'Walmart Inc.', initialPrice: 140, currentPrice: 140, description: 'Multinational retail corporation operating hypermarkets.', ipoDate: '1972-08-25', siteUrl: 'https://walmart.com', industries: ['Retail'], icon: 'https://www.google.com/s2/favicons?domain=walmart.com&sz=128', favorited: false },
  { id: 14, ticker: 'PYPL', exchange: 'NASDAQ', name: 'PayPal Holdings Inc.', initialPrice: 270, currentPrice: 270, description: 'Online payments system supporting money transfers worldwide.', ipoDate: '2015-07-20', siteUrl: 'https://paypal.com', industries: ['Finance'], icon: 'https://www.google.com/s2/favicons?domain=paypal.com&sz=128', favorited: false },
  { id: 15, ticker: 'INTC', exchange: 'NASDAQ', name: 'Intel Corporation', initialPrice: 55, currentPrice: 55, description: 'Multinational technology and semiconductor company.', ipoDate: '1971-10-13', siteUrl: 'https://intel.com', industries: ['Semiconductors'], icon: 'https://www.google.com/s2/favicons?domain=intel.com&sz=128', favorited: false },
  { id: 16, ticker: 'UBER', exchange: 'NYSE', name: 'Uber Technologies Inc.', initialPrice: 45, currentPrice: 45, description: 'Technology company offering ride-hailing and food delivery.', ipoDate: '2019-05-10', siteUrl: 'https://uber.com', industries: ['Transportation'], icon: 'https://www.google.com/s2/favicons?domain=uber.com&sz=128', favorited: false },
  { id: 17, ticker: 'SPOT', exchange: 'NYSE', name: 'Spotify Technology', initialPrice: 250, currentPrice: 250, description: 'Audio streaming and media services provider.', ipoDate: '2018-04-03', siteUrl: 'https://spotify.com', industries: ['Entertainment'], icon: 'https://www.google.com/s2/favicons?domain=spotify.com&sz=128', favorited: false },
  { id: 18, ticker: 'TWTR', exchange: 'NYSE', name: 'Twitter Inc.', initialPrice: 65, currentPrice: 65, description: 'Social media and microblogging platform.', ipoDate: '2013-11-07', siteUrl: 'https://twitter.com', industries: ['Social Media'], icon: 'https://www.google.com/s2/favicons?domain=twitter.com&sz=128', favorited: false },
  { id: 19, ticker: 'SHOP', exchange: 'NYSE', name: 'Shopify Inc.', initialPrice: 1400, currentPrice: 1400, description: 'E-commerce platform for online stores and retail.', ipoDate: '2015-05-21', siteUrl: 'https://shopify.com', industries: ['E-Commerce'], icon: 'https://www.google.com/s2/favicons?domain=shopify.com&sz=128', favorited: false },
  { id: 20, ticker: 'ZOOM', exchange: 'NASDAQ', name: 'Zoom Video Communications', initialPrice: 350, currentPrice: 350, description: 'Video telecommunications and online chat services.', ipoDate: '2019-04-18', siteUrl: 'https://zoom.us', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=zoom.us&sz=128', favorited: false },
  { id: 21, ticker: 'AMD', exchange: 'NASDAQ', name: 'Advanced Micro Devices', initialPrice: 90, currentPrice: 90, description: 'Semiconductor company developing processors and graphics cards.', ipoDate: '1979-09-27', siteUrl: 'https://amd.com', industries: ['Semiconductors'], icon: 'https://www.google.com/s2/favicons?domain=amd.com&sz=128', favorited: false },
  { id: 22, ticker: 'BA', exchange: 'NYSE', name: 'Boeing Company', initialPrice: 220, currentPrice: 220, description: 'Aerospace and defense manufacturer of aircraft.', ipoDate: '1962-01-01', siteUrl: 'https://boeing.com', industries: ['Aerospace'], icon: 'https://www.google.com/s2/favicons?domain=boeing.com&sz=128', favorited: false },
  { id: 23, ticker: 'GS', exchange: 'NYSE', name: 'Goldman Sachs Group', initialPrice: 380, currentPrice: 380, description: 'Global investment banking and securities firm.', ipoDate: '1999-05-04', siteUrl: 'https://goldmansachs.com', industries: ['Finance'], icon: 'https://www.google.com/s2/favicons?domain=goldmansachs.com&sz=128', favorited: false },
  { id: 24, ticker: 'CRM', exchange: 'NYSE', name: 'Salesforce Inc.', initialPrice: 250, currentPrice: 250, description: 'Cloud-based software company for customer relationship management.', ipoDate: '2004-06-23', siteUrl: 'https://salesforce.com', industries: ['Software'], icon: 'https://www.google.com/s2/favicons?domain=salesforce.com&sz=128', favorited: false },
  { id: 25, ticker: 'ORCL', exchange: 'NYSE', name: 'Oracle Corporation', initialPrice: 90, currentPrice: 90, description: 'Technology corporation selling database software and cloud systems.', ipoDate: '1986-03-12', siteUrl: 'https://oracle.com', industries: ['Software'], icon: 'https://www.google.com/s2/favicons?domain=oracle.com&sz=128', favorited: false },
  { id: 26, ticker: 'ADBE', exchange: 'NASDAQ', name: 'Adobe Inc.', initialPrice: 650, currentPrice: 650, description: 'Software company known for creative and multimedia software.', ipoDate: '1986-08-13', siteUrl: 'https://adobe.com', industries: ['Software'], icon: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=128', favorited: false },
  { id: 27, ticker: 'ABNB', exchange: 'NASDAQ', name: 'Airbnb Inc.', initialPrice: 175, currentPrice: 175, description: 'Online marketplace for lodging and tourism experiences.', ipoDate: '2020-12-10', siteUrl: 'https://airbnb.com', industries: ['Travel'], icon: 'https://www.google.com/s2/favicons?domain=airbnb.com&sz=128', favorited: false },
  { id: 28, ticker: 'LYFT', exchange: 'NASDAQ', name: 'Lyft Inc.', initialPrice: 55, currentPrice: 55, description: 'Ride-sharing and transportation network company.', ipoDate: '2019-03-29', siteUrl: 'https://lyft.com', industries: ['Transportation'], icon: 'https://www.google.com/s2/favicons?domain=lyft.com&sz=128', favorited: false },
  { id: 29, ticker: 'SQ', exchange: 'NYSE', name: 'Block Inc.', initialPrice: 250, currentPrice: 250, description: 'Financial services and digital payments company.', ipoDate: '2015-11-19', siteUrl: 'https://block.xyz', industries: ['Finance'], icon: 'https://www.google.com/s2/favicons?domain=block.xyz&sz=128', favorited: false },
  { id: 30, ticker: 'SNAP', exchange: 'NYSE', name: 'Snap Inc.', initialPrice: 65, currentPrice: 65, description: 'Camera and social media company behind Snapchat.', ipoDate: '2017-03-02', siteUrl: 'https://snap.com', industries: ['Social Media'], icon: 'https://www.google.com/s2/favicons?domain=snap.com&sz=128', favorited: false },
  { id: 31, ticker: 'PINS', exchange: 'NYSE', name: 'Pinterest Inc.', initialPrice: 65, currentPrice: 65, description: 'Image sharing and social media platform.', ipoDate: '2019-04-18', siteUrl: 'https://pinterest.com', industries: ['Social Media'], icon: 'https://www.google.com/s2/favicons?domain=pinterest.com&sz=128', favorited: false },
  { id: 32, ticker: 'COIN', exchange: 'NASDAQ', name: 'Coinbase Global Inc.', initialPrice: 380, currentPrice: 380, description: 'Cryptocurrency exchange and trading platform.', ipoDate: '2021-04-14', siteUrl: 'https://coinbase.com', industries: ['Finance'], icon: 'https://www.google.com/s2/favicons?domain=coinbase.com&sz=128', favorited: false },
  { id: 33, ticker: 'RBLX', exchange: 'NYSE', name: 'Roblox Corporation', initialPrice: 75, currentPrice: 75, description: 'Online game platform and game creation system.', ipoDate: '2021-03-10', siteUrl: 'https://roblox.com', industries: ['Gaming'], icon: 'https://www.google.com/s2/favicons?domain=roblox.com&sz=128', favorited: false },
  { id: 34, ticker: 'HOOD', exchange: 'NASDAQ', name: 'Robinhood Markets Inc.', initialPrice: 38, currentPrice: 38, description: 'Financial services company offering commission-free trading.', ipoDate: '2021-07-29', siteUrl: 'https://robinhood.com', industries: ['Finance'], icon: 'https://www.google.com/s2/favicons?domain=robinhood.com&sz=128', favorited: false },
  { id: 35, ticker: 'TWLO', exchange: 'NYSE', name: 'Twilio Inc.', initialPrice: 400, currentPrice: 400, description: 'Cloud communications platform as a service company.', ipoDate: '2016-06-23', siteUrl: 'https://twilio.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=twilio.com&sz=128', favorited: false },
  { id: 36, ticker: 'DOCU', exchange: 'NASDAQ', name: 'DocuSign Inc.', initialPrice: 290, currentPrice: 290, description: 'Electronic signature and digital transaction management company.', ipoDate: '2018-04-27', siteUrl: 'https://docusign.com', industries: ['Software'], icon: 'https://www.google.com/s2/favicons?domain=docusign.com&sz=128', favorited: false },
  { id: 37, ticker: 'PLTR', exchange: 'NYSE', name: 'Palantir Technologies', initialPrice: 25, currentPrice: 25, description: 'Software company specializing in big data analytics.', ipoDate: '2020-09-30', siteUrl: 'https://palantir.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=palantir.com&sz=128', favorited: false },
  { id: 38, ticker: 'SNOW', exchange: 'NYSE', name: 'Snowflake Inc.', initialPrice: 330, currentPrice: 330, description: 'Cloud-based data warehousing and analytics company.', ipoDate: '2020-09-16', siteUrl: 'https://snowflake.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=snowflake.com&sz=128', favorited: false },
  { id: 39, ticker: 'NET', exchange: 'NYSE', name: 'Cloudflare Inc.', initialPrice: 130, currentPrice: 130, description: 'Web infrastructure and website security company.', ipoDate: '2019-09-13', siteUrl: 'https://cloudflare.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=128', favorited: false },
  { id: 40, ticker: 'DDOG', exchange: 'NASDAQ', name: 'Datadog Inc.', initialPrice: 160, currentPrice: 160, description: 'Monitoring and analytics platform for developers and IT teams.', ipoDate: '2019-09-19', siteUrl: 'https://datadoghq.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=datadoghq.com&sz=128', favorited: false },
  { id: 41, ticker: 'MCD', exchange: 'NYSE', name: 'McDonalds Corporation', initialPrice: 250, currentPrice: 250, description: 'Multinational fast food corporation and restaurant chain.', ipoDate: '1965-04-21', siteUrl: 'https://mcdonalds.com', industries: ['Food'], icon: 'https://www.google.com/s2/favicons?domain=mcdonalds.com&sz=128', favorited: false },
  { id: 42, ticker: 'KO', exchange: 'NYSE', name: 'Coca-Cola Company', initialPrice: 55, currentPrice: 55, description: 'Beverage corporation manufacturing soft drinks worldwide.', ipoDate: '1919-09-05', siteUrl: 'https://coca-cola.com', industries: ['Beverages'], icon: 'https://www.google.com/s2/favicons?domain=coca-cola.com&sz=128', favorited: false },
  { id: 43, ticker: 'PEP', exchange: 'NASDAQ', name: 'PepsiCo Inc.', initialPrice: 155, currentPrice: 155, description: 'Multinational food and beverage corporation.', ipoDate: '1972-01-01', siteUrl: 'https://pepsico.com', industries: ['Beverages'], icon: 'https://www.google.com/s2/favicons?domain=pepsico.com&sz=128', favorited: false },
  { id: 44, ticker: 'NKE', exchange: 'NYSE', name: 'Nike Inc.', initialPrice: 165, currentPrice: 165, description: 'Multinational corporation designing athletic footwear and apparel.', ipoDate: '1980-12-02', siteUrl: 'https://nike.com', industries: ['Apparel'], icon: 'https://www.google.com/s2/favicons?domain=nike.com&sz=128', favorited: false },
  { id: 45, ticker: 'SBUX', exchange: 'NASDAQ', name: 'Starbucks Corporation', initialPrice: 115, currentPrice: 115, description: 'Multinational chain of coffeehouses and roastery reserves.', ipoDate: '1992-06-26', siteUrl: 'https://starbucks.com', industries: ['Food'], icon: 'https://www.google.com/s2/favicons?domain=starbucks.com&sz=128', favorited: false },
  { id: 46, ticker: 'IBM', exchange: 'NYSE', name: 'IBM Corporation', initialPrice: 140, currentPrice: 140, description: 'Multinational technology and IT consulting corporation.', ipoDate: '1915-01-01', siteUrl: 'https://ibm.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=ibm.com&sz=128', favorited: false },
  { id: 47, ticker: 'QCOM', exchange: 'NASDAQ', name: 'Qualcomm Inc.', initialPrice: 145, currentPrice: 145, description: 'Semiconductor and telecommunications equipment company.', ipoDate: '1991-12-13', siteUrl: 'https://qualcomm.com', industries: ['Semiconductors'], icon: 'https://www.google.com/s2/favicons?domain=qualcomm.com&sz=128', favorited: false },
  { id: 48, ticker: 'CSCO', exchange: 'NASDAQ', name: 'Cisco Systems Inc.', initialPrice: 55, currentPrice: 55, description: 'Technology conglomerate selling networking hardware and software.', ipoDate: '1990-02-16', siteUrl: 'https://cisco.com', industries: ['Technology'], icon: 'https://www.google.com/s2/favicons?domain=cisco.com&sz=128', favorited: false },
  { id: 49, ticker: 'SPCE', exchange: 'NYSE', name: 'Virgin Galactic Holdings', initialPrice: 25, currentPrice: 25, description: 'Spaceflight company developing commercial spacecraft.', ipoDate: '2019-10-28', siteUrl: 'https://virgingalactic.com', industries: ['Aerospace'], icon: 'https://www.google.com/s2/favicons?domain=virgingalactic.com&sz=128', favorited: false },
  { id: 50, ticker: 'RIVN', exchange: 'NASDAQ', name: 'Rivian Automotive Inc.', initialPrice: 100, currentPrice: 100, description: 'Electric vehicle automaker and automotive technology company.', ipoDate: '2021-11-10', siteUrl: 'https://rivian.com', industries: ['Automotive'], icon: 'https://www.google.com/s2/favicons?domain=rivian.com&sz=128', favorited: false }
];

mongoose.connect(process.env.MONGO_CONNECTION_STRING)
.then(() => Stock.deleteMany({}))
.then(() => Stock.insertMany(stocks))
.then(() => { console.log('50 STOCKS INSERTED!'); process.exit(0); })
.catch(e => { console.log('ERROR:', e.message); process.exit(1); });
